### ISSUE TITLE
Test / implement time types for Microsoft SQL Server

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quick-sql-test-data#20]
This issue aims to add automatic tests for _Microsoft SQL Server_ time types (Date, Timestamp, Timestamp with time zone, Time, Time with time zone, ...). Test examples are available in `PostgreSqlTest` class. If _SQL test data generator_ does not manage a time type for _Microsoft SQL Server_  yet, please update the `ColumnValueFormatter` class to make it works.

**Comment by raychenon** [comment]
I will start with this one.

**Comment by jeanbisutti** [comment]
Fixed with bc4859a83d593e39df92a068e73392f7429d5771 Thank you @raychenon
