### ISSUE TITLE
Add Maven badge on Readme

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quick-sql-test-data#9]
This issue aims to add a Maven badge on the Readme to display the current version deployed on Maven Central:

![image](https://user-images.githubusercontent.com/14811066/120031014-7a533480-bff8-11eb-98c5-97719aca820d.png)

You can find an example on [QuickPerf Readme](https://github.com/quick-perf/quickperf/blob/master/README.md).

**Comment by jlecordier** [comment]
On it
